// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using Azure.Core;

namespace Azure.WindowsWirtualDesktop
{
    /// <summary> Client options for WindowsWirtualDesktop. </summary>
    public class WindowsWirtualDesktopManagementClientOptions : ClientOptions
    {
    }
}
